export interface Env extends Omit<
  Cloudflare.Env,
  | "CHAT_MODEL"
  | "BACKGROUND_MODEL"
  | "BATCH_MODEL"
  | "PROACTIVE_DISABLED"
  | "OPENROUTER_PROVIDER"
  | "BACKGROUND_REASONING_EFFORT"
  | "IDENTITY"
  | "BROWSER"
  | "CODE_LOADER"
> {
  CODE_LOADER?: WorkerLoader;
  BROWSER?: Fetcher;
  MEMORY_INDEX?: VectorizeIndex;
  DOCUMENT_INDEX?: VectorizeIndex;
  AUTH?: Fetcher;
  AGENT_TOKEN?: string;
  ACCESS_TEAM_DOMAIN?: string;
  ACCESS_AUD?: string;
  ACCESS_OWNER_EMAIL?: string;
  AUTH_ORIGIN?: string;
  AUTH_SECRET?: string;
  IDENTITY?: DurableObjectNamespace<
    import("../identity/IdentityDO").IdentityDO
  >;
  TELEGRAM_BOT_TOKEN?: string;
  TELEGRAM_WEBHOOK_SECRET?: string;
  CONNECTORS?: Fetcher;
  CONNECTOR_AUTH_SECRET?: string;
  INTERNAL_AUTH_SECRET: string;
  MCP_CREDENTIALS_SECRET?: string;
  OPENROUTER_API_KEY?: string;
  OPENROUTER_BASE_URL?: string;
  OPENROUTER_PROVIDER?: string;
  BACKGROUND_REASONING_EFFORT?: string;
  CHAT_MODEL: string;
  BACKGROUND_MODEL: string;
  BATCH_MODEL: string;
  PROACTIVE_DISABLED?: string;
  LOCAL_DEV?: string;
  ENVIRONMENT?: string;
  OTLP_ENDPOINT?: string;
  OTLP_HEADERS?: string;
  OTEL_TRACE_SAMPLE_RATE?: string;
  OTEL_TRACE_SLOW_MS?: string;
  OTEL_EXPORTER_OTLP_ENDPOINT?: string;
  OTEL_EXPORTER_OTLP_HEADERS?: string;
  OTEL_SERVICE_NAME?: string;
  OTEL_TRACES_SAMPLER_ARG?: string;
  OTEL_TAIL_SAMPLE_RATE?: string;
  WAKE_MAX_DAILY_TRIAGE_TURNS?: string;
  WAKE_MAX_DAILY_SUBAGENT_SPAWNS?: string;
  WAKE_MAX_NOTIFICATIONS_PER_WAKE?: string;
  WAKE_SIGNAL_DEDUPE_TTL_MS?: string;
  WAKE_SIGNAL_DEDUPE_TTL_HOURS?: string;
  WAKE_DAILY_MAX_TOKENS?: string;
  WAKE_DAILY_MAX_SUBAGENTS?: string;
  WAKE_NOTIFICATION_CAP?: string;
  WAKE_SIGNAL_DEDUPE_TTL_DAYS?: string;
}
